// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { supabasePublishableKey, supabaseUrl } from './env';
import { localhostProductionWriteGuardFetch } from './localhostWriteGuard';

if (!supabaseUrl || !supabasePublishableKey) {
  throw new Error(
    "Supabase env belum terisi. Isi VITE_SUPABASE_URL + VITE_SUPABASE_PUBLISHABLE_KEY atau NEXT_PUBLIC_SUPABASE_URL + NEXT_PUBLIC_SUPABASE_ANON_KEY."
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabasePublishableKey, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  global: {
    fetch: localhostProductionWriteGuardFetch,
  },
});
